### ISSUE TITLE
Add tagging system

### ISSUE THREAD

**Issue by Lyla-Fischer** [AnanseGroup/atlas_of_innovation#15]
This one is a big one. 

Use [django-taggit](https://django-taggit.readthedocs.io/en/latest/). 

Make the search bar be able to search by tag. 

Pre-populate accepted tags according to https://docs.google.com/document/d/1U9BwfkqsDpekBjB9DkHUnKrLJigaIYWK0HX6zuM9Nv0/edit#

**Comment by annawb** [comment]
Is this part of the search milestone?

**Comment by Lyla-Fischer** [comment]
It is now.

**Comment by Lyla-Fischer** [comment]
This was done with a multiselectfield rather than a tagging system.
