### ISSUE TITLE
Tricky datafields that need further discussion

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/atlas_of_innovation#16]
- [ ] Membership/cost structure
- [x] Governance
- [ ] Capabilities (listing tools)

How about we wait to see if we've got funding, and then ask the community to check out our datafields if funding is confirmed? I'd really like to do one more pass on the datafields with community members...

**Comment by Lyla-Fischer** [comment]
My understanding of these three fields is that we have a nice set of choices for Governance, that we are okay with a free response for membership/cost structure, and that we are putting off a tool listing and letting Makernet worry about that. 

@annawb @dottiemaej Is that a close enough conclusion that we can close this issue?

**Comment by annawb** [comment]
Sounds good to me, thanks!
