### ISSUE TITLE
Have an editable space profile page

### ISSUE THREAD

**Issue by Lyla-Fischer** [AnanseGroup/atlas_of_innovation#2]
All of the fields with their own fields should be displayed as options, even if they don't have any data for them. There is a JSONField for everything else. It will look messy, but this way at least the data is out there.

**Comment by Lyla-Fischer** [comment]
Display information from the JSONField as their own little mini-fields, but leave a label indicating that the data contained in it is not searchable. Use an asterisk with the help text "The data in this field is not currently searchable. If you are willing to contribute to the community, please help us transfer the data in this field to a searchable field."

**Comment by annawb** [comment]
https://docs.google.com/document/d/1b7hzdPvyi-BHgLt7yiP49csZhT8JcG_xPInlELJv2xE/edit

**Comment by Lyla-Fischer** [comment]
Make sure to include the ability to add and delete spaces

**Comment by Lyla-Fischer** [comment]
https://github.com/AnanseGroup/atlas_of_innovation/pull/28
