### ISSUE TITLE
Be able to get a whitelabel map with search criteria in it, including being able to search based off of network affiliation

### ISSUE THREAD

**Issue by Lyla-Fischer** [AnanseGroup/atlas_of_innovation#31]

**Comment by Lyla-Fischer** [comment]
This should be generated with a URL API call so that users can easily put it together and integrate into their organization websites.

**Comment by Lyla-Fischer** [comment]
This should include documentation on how to use it and how to integrate it via iframe into someone's website.

**Comment by Lyla-Fischer** [comment]
Here is an example of a site that would use such a feaure: https://www.globalinnovationgathering.org/meet-members/

**Comment by dottiemaej** [comment]
Love this! This is one thing that we’d love to do with our subset of
members of NoM that are on the map.

Best,
Dorothy

**Comment by Lyla-Fischer** [comment]
Here are the fablab search criteria, embedded with the API. https://github.com/fablabbcn/fablabs.io/blob/master/apiary.apib

**Comment by Lyla-Fischer** [comment]
In order to satisfy the Nation of Makers use case, I also need to have the map be able to:
(1) focus on a region (specifically the US), and 
(2) I need to add a field that says whether a space is associated with Nation of Makers, and make it search-able using the query.

**Comment by annawb** [comment]
Sounds great! For (2), the existing field “Network_Affiliation” is the one that should list networks like NoM.
