### ISSUE TITLE
Improve response time of loading the map

### ISSUE THREAD

**Issue by Lyla-Fischer** [AnanseGroup/atlas_of_innovation#50]
The map is painfully slow to load. Improve the load time to something more reasonable than 23 seconds.

**Comment by Lyla-Fischer** [comment]
I made it so that we only return the information that we actually use to render the map, and now we are taking about four seconds to load. more than 5x speedup for the win!

**Comment by annawb** [comment]
WOAH THAT’S SO FAST

**Comment by Lyla-Fischer** [comment]
There is even more room for speedup if we do stuff with the map so that we only send aggregates instead of having to send the entire database in order to display it, but I figure that this is good enough for now. We have the little load-y spin thing. Four seconds is acceptable if we have the little load-y spin thing.
