### ISSUE TITLE
Make a staging environment for deployment

### ISSUE THREAD

**Issue by Lyla-Fischer** [AnanseGroup/atlas_of_innovation#51]
The next major deploy should have the current environment in production, with atlasofinnovation.com pointing at it. Therefore we should have a staging environment to practice the deployment before doing it for real, and maintaining uptime. 

It's going to be another giant pain in the butt, but it's good deployment practice.

**Comment by Lyla-Fischer** [comment]
I made a staging environment, but I'm not satisfied with where I left it. I ended up working directly on production for most of this. What *should* happen, is to make a staging environment that can
1) work with a copy of production data, so that we can practice data manipulations before doing them in production. Does this in an environment-specific way (so figure out how to put different config variables into different environments from the same repo)
2) automatically updates the CORS policy, instead of me having to go into the server itself to change it manually. (That won't scale across instances. It's mostly okay for now, because we aren't using any of the autoscaling services of elasticbeanstalk, but as it stands, it makes it look like we are just using unecessary infrastructure that will break as soon as it becomes necessary.)

**Comment by Lyla-Fischer** [comment]
I figured out how to do (1), but not in a programmatic way. You have to go into the uploaded environment config file with `eb config atlasEnv-staging` and change the SnapshotImage to the appropriate snapshot that you want to replicate in the staging environment. Snapshots are taken at regular intervals for data integrity, so they are not hard to come up with, but it takes like a half hour for the new database to spin up and be associated with the staging environment. Therefore we should probably not include the most recent snapshot as a regular part of staging, just because it will take too long to deploy every time, in addition to the fact that there doesn't seem to be an automated way to do it anyway.

**Comment by Rojo** [comment]
@JonSemarge Helped me to spin up an new instance for staging. It is already working and we just need to define if some configuration settings should be applied to it (recaptcha and SSL).

**Comment by Rojo** [comment]
Staging instance configuration is now complete.
