### ISSUE TITLE
Internationalize the phone number field

### ISSUE THREAD

**Issue by Lyla-Fischer** [AnanseGroup/atlas_of_innovation#8]
Phone numbers come in lots of different forms, and we should be able to accept any of them. Initial implementation is to just make the phone number field an unvalidated char field, but we should put more validation against the field. There is a package for it here: https://github.com/stefanfoulis/django-phonenumber-field/tree/master/phonenumber_field

**Comment by Lyla-Fischer** [comment]
The package isn't quite plug-and-play, and there isn't an awful lot of advantage to having a standardized format for the phone numbers. It's not like we are autodialing anything. I'm closing this issue without implementing it, and will keep the CharField implementation.

**Comment by annawb** [comment]
Sounds good!
