### ISSUE TITLE
Missing CORS header blocks different domain API call

### ISSUE THREAD

**Issue by Rojo** [AnanseGroup/atlas_of_innovation#91]
Recently, the API call from the MakerNet instances started to be blocked by the browsers with the following message:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.atlasofinnovation.com/api/space/filter/?not_closed=True&fields=latitude,longitude,name,city,country,website,short_description,id&cache=true. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)`

From what I've researched, the clients (browsers) require the response to include the following header:

`Access-Control-Allow-Origin: *`

The alternative is to prepare the API to handle `JSONP` requests, which are not blocked by the same origin policy, by detecting the parameter `callback=someFunction` in the API call, and return the JSON object wrapped by that specific function, like: `someFunction({"Name": "Foo", "Id": 1234, "Rank": 7});`.

Here is an example on how to define a decorator in Django to apply JSON/JSONP serialization: https://coderwall.com/p/k8vb_a/returning-json-jsonp-from-a-django-view-with-a-little-decorator-help

**Comment by Rojo** [comment]
@Lyla-Fischer @pedroquiroz Please let us know your resolution on this to implement the required changes in _MaketNet Alpha_ accordingly.

**Comment by Lyla-Fischer** [comment]
Ya, I fixed it manually when I launched the first time, and I suspect that ElasticBeanstalk spun up a new instance, and didn't transfer that manual setting.

**Comment by pedro-q** [comment]
I think this can be solved by installing a Django module, let me check and I'll make the proper commit.
